
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: apikey-auth-server
            uri: http://localhost:9000
            predicates:
              - Path=/oauth2/**
          - id: test-client
            uri: http://localhost:9090
            predicates:
              - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG